
{"asctime": "2025-04-21 13:17:31,942", "levelname": "ERROR", "name": "bot", "message": "Handled exception in User", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\Dmitriy\\Desktop\\Bless-bot\\modules\\users\\User.py\", line 93, in set_photo\n    photo = message.photo[-1]\n            ~~~~~~~~~~~~~^^^^\nTypeError: 'NoneType' object is not subscriptable", "exception": "User didnt send photo", "user_id": 1045393239, "user_name": "Mandarinchik2315"}
{"asctime": "2025-04-21 13:17:34,939", "levelname": "ERROR", "name": "bot", "message": "Handled exception in User", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\Dmitriy\\Desktop\\Bless-bot\\modules\\users\\User.py\", line 93, in set_photo\n    photo = message.photo[-1]\n            ~~~~~~~~~~~~~^^^^\nTypeError: 'NoneType' object is not subscriptable", "exception": "User didnt send photo", "user_id": 1045393239, "user_name": "Mandarinchik2315"}
{"asctime": "2025-04-26 13:34:12,145", "levelname": "ERROR", "name": "bot", "message": "Handled exception in User", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\Dmitriy\\Desktop\\Bless-bot\\modules\\users\\User.py\", line 136, in send_order\n    await self._bot.send_photo(chat_id=self.__admin_id, photo=photo, caption=f\"\"\"\u0417\u0430\u043a\u0430\u0437 \u043e\u0442 {self._user_link}\\n{orderPositions}\"\"\")\n  File \"C:\\Users\\Dmitriy\\Desktop\\Bless-bot\\venv\\Lib\\site-packages\\aiogram\\client\\bot.py\", line 2895, in send_photo\n    return await self(call, request_timeout=request_timeout)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dmitriy\\Desktop\\Bless-bot\\venv\\Lib\\site-packages\\aiogram\\client\\bot.py\", line 453, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dmitriy\\Desktop\\Bless-bot\\venv\\Lib\\site-packages\\aiogram\\client\\session\\base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dmitriy\\Desktop\\Bless-bot\\venv\\Lib\\site-packages\\aiogram\\client\\session\\aiohttp.py\", line 185, in make_request\n    response = self.check_response(\n               ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dmitriy\\Desktop\\Bless-bot\\venv\\Lib\\site-packages\\aiogram\\client\\session\\base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: chat not found", "exception": "Chat_not_found"}
